### ISSUE TITLE
Upgrade to Metrics 3.1

### ISSUE THREAD

**Issue by analytically** [riemann/riemann-java-client#43]
https://groups.google.com/forum/#!topic/metrics-user/zwzHnMBcAX4

For this and all subsequent releases the group id has changed to 'io.dropwizard.metrics'.  However, for backwards compatibility with the 3.0 release, the java package is still 'com.codahale.metrics'.  Yes, this is perhaps slightly confusing, but the alternative was to break backwards compatibility and all third party modules.

**Comment by jamtur01** [comment]
Upgrade will be in next release.
