### ISSUE TITLE
Use Daemon Threads

### ISSUE THREAD

**Issue by shanielh** [riemann/riemann-java-client#63]
Hi!

I'm using the riemann-java-client, When an unhandled exception is thrown in some thread, The program doesn't die because riemann-client starts threads in "non-daemon" mode.

The default c'tor HashedWheelTimer of netty uses the defaultThreadFactory which starts threads in non-daemon mode.

**Comment by dfrese** [comment]
Seem to me this was fixed in 0.4.2 (https://github.com/riemann/riemann-java-client/pull/67).
Correct?

**Comment by shanielh** [comment]
Yes :)

**Comment by dfrese** [comment]
Sorry, but now that I tried there is still something left.
I see many threads created for each riemann client: 2 'Hashed wheel timer' (!), 1 "New I/O boss" and 8 "New I/O worker". In 0.4.1 all were non-daemon threads; with 0.4.3 one of the timers is now a daemon, but all others are still non-daemon.

Any ideas/help welcome; as I'm pretty sure this is still preventing my process from quitting.
