### ISSUE TITLE
Issue with event time resolution

### ISSUE THREAD

**Issue by mmatloka** [riemann/riemann-java-client#64]
Hi,
I use `riemann-java-client` to pass events from application via riemann to influxdb. Influxdb saves data with timestamp represented in `ns` (https://influxdb.com/docs/v0.9/concepts/glossary.html#timestamp ). When I create an event in `riemann-java-client` and don't specify manually a `.time(...)`  I can see in Rieman an entry with e.g. `:time 1.445608905415E9` (automatically generated). `1.445608905415E9 = 1445608905.415` so its a floating point numer. In Riemann docs it is said that this time is  `The time of the event, in unix epoch seconds` so this means the data resolution in Riemann is to `ms`. However when using `riemann-java-client` methods `.time(long/double/float)` does inside a casting (https://github.com/aphyr/riemann-java-client/blob/486d2e0bb8de1c296c3ed3f6c8e05c57c7fcb9dc/riemann-java-client/src/main/java/com/aphyr/riemann/client/EventDSL.java#L75) to long, so even when I pass a floating point (e.g. `1.445609498551E9`) which represents time with resolution to `ms` it looses `ms` (`1.445609498551E9 -> 1445609498`) and the client sends to riemann always an integer value with resolution to `s` . Due to that then I get more `collisions` - more events with exactly same time (with resolution to `s`) and influx can have only one entry with exactly the same timestamp.

What is a proper way to specify manually time in `riemann-java-client` ? Or is this a bug?

**Comment by aphyr** [comment]
On 10/23/2015 07:17 AM, Michal Matloka wrote:
> Due to that then I get more |collisions| - more events with
> exactly same time (with resolution to |s|) and influx can have only one entry
> with exactly the same timestamp.
>
> What is a proper way to specify manually time in |riemann-java-client| ? Or is
> this a bug?

Riemann's protocol uses integer seconds as its temporal resolution. At some 
point I'd like to rebase to, say, micros, but that'll require a coordinated 
change of the streaming system, all integrations, and compatibility layers for 
mixed clients.

--Kyle

**Comment by jamtur01** [comment]
Should be fixed by #80
