### ISSUE TITLE
Missing tags for recent releases

### ISSUE THREAD

**Issue by jcf** [riemann/riemann-java-client#77]
Hello there!

I'm not sure if the tags have been created, but they've definitely not been pushed to GitHub with `git push --tags ...`. Can we get the missing tags created, and pushed please?

https://github.com/riemann/riemann-java-client/tags

I also noticed and [commented on the release process docs commit](https://github.com/riemann/riemann-java-client/commit/94d822bc8ff451aeae4ce34aacec6e7202f1a27b#commitcomment-19980862) that tags aren't mentioned.

**Comment by jamtur01** [comment]
Done.

**Comment by jcf** [comment]
@jamtur01 Thank you!
