### ISSUE TITLE
Upgrade to latest dropwizard metrics

### ISSUE THREAD

**Issue by eranharel** [riemann/riemann-java-client#87]
The latest dropwizard metrics (4.x.x) removed a lot of clutter, and is now Java 8 based and supports Java 9.
Now that the older (< 8) Java versions are EOL it makes sense to upgrade.
Is there a plan to upgrade this project?

I'm not a direct user of this project, just trying to upgrade [metrics-clojure](https://github.com/metrics-clojure).

**Comment by jamtur01** [comment]
It's been done in 0.5.1-SNAPSHOT. Will be in next release.
