### ISSUE TITLE
metrics3-riemann-reporter depends on metrics 4

### ISSUE THREAD

**Issue by pburka** [riemann/riemann-java-client#95]
In 0.5.1, the metrics3-riemann-reporter metrics dependency was upgraded from 3.1.5 to 4.0.2. In the same release, a metrics4-riemann-reporter artifact was added, which also depends on 4.0.2.

Is this correct, and, if so, what is the difference between the metrics3 and metrics4 artifacts?

**Comment by jamtur01** [comment]
Fixed in 903b031091eaeb608fc5f78a6b065cab41f57434.
